#!/usr/bin/env bash
# installs nginx and configures it on a remote server and listens to port 80

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
