#!/usr/bin/env bash

# this prints fizz buzz

x=1

while [ $x -le 100 ]
do
    if [ $((x % 3)) -eq 0 ]; then
        echo "Fizz"
    elif [ $((x % 5)) -eq 0 ]; then
        echo "Buzz"
    elif [ $((x % 3)) -eq 0 ] && [ $((x % 5)) -eq 0 ]; then
        echo "FizzBuzz"
    else
        echo "$x"
    fi
    ((x++))
done
