#!/usr/bin/env bash
#this displays hi at the 9th iteration

x=1
while [ $x -le 10 ]
do
    if [ $x -eq 9 ]
    then
        echo "Best School"
        echo "hi"
    else
        echo "Best School"
    fi
    ((x++))
done
