#!/usr/bin/bash
# this confugure the the server to listen to port 80, 443, 22
sudo apt-get update
sudo apt-install -y ufw
sudo ufw default deny incoming
sudo ufw default allow incoming
sudo ufw allow 22
sudo ufw allow 80
sudo ufw allow 443
sudo ufw enable
